--- #YAML:1.0
name:                Pod-InDesign-TaggedText
version:             0.11
abstract:            Convert Pod to InDesign's Tagged Text format
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Pod::PseudoPod:                0
    Test::LongString:              0
    Tie::Cycle:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
